<a href="https://colab.research.google.com/github/angarikadas26-lgtm/burnout-prediction-project/blob/main/ArtifactV2_datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!pip install pandas numpy matplotlib seaborn scikit-learn xgboost shap

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (0.51.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap) (4.67.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from shap) (0.60.0)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.12/dist-packages (from shap) (0.43.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# IS6611 Applied Research in Business Analytics
# Employee Burnout Prediction
# Group 6

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#read file
df = pd.read_csv(
    '/content/drive/MyDrive/Artefact V2/2024_Eurofound_working_conditions.csv')

/tmp/ipykernel_18258/1709392518.py:2: DtypeWarning: Columns (9,16,43,44,46,48,52,54,55,62,101,102,110,111,127,133,208,212,217,232,243,245,256,258,259,260,288,324,325,334,366,378) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [6]:
#data description
df.head()
df.shape

(36644, 386)

In [7]:
#Step 1-understand (analyze) & clean data
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36644 entries, 0 to 36643
Columns: 386 entries, uniquerespid to calweight
dtypes: float64(7), int64(34), object(345)
memory usage: 107.9+ MB

uniquerespid       0
country_code       0
country            0
language           0
samplingpointid    0
                  ..
sector             0
region             0
design_weight      0
gweight            0
calweight          0
Length: 386, dtype: int64

In [8]:
#check missing values
missing_values = df.isnull().sum()

missing_values.sort_values(ascending=False)

calweight           0
uniquerespid        0
boss_conf           0
boss_cooperation    0
boss_respect        0
                   ..
stratumid           0
householdnumber     0
samplingpointid     0
language            0
country             0
Length: 386, dtype: int64

In [9]:
#Missing Percentage

missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent.sort_values(ascending=False)

calweight           0.0
uniquerespid        0.0
boss_conf           0.0
boss_cooperation    0.0
boss_respect        0.0
                   ...
stratumid           0.0
householdnumber     0.0
samplingpointid     0.0
language            0.0
country             0.0
Length: 386, dtype: float64

In [10]:
#identify data types
df.dtypes.value_counts()

object     345
int64       34
float64      7
Name: count, dtype: int64

In [11]:
#Separate Numerical and Categorical Columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

categorical_cols = df.select_dtypes(include=['object']).columns

In [12]:
#check duplicate rows
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,country,language,householdnumber,degurba,ISCO_2,ISCO_1,NACE_2,improve_pay_benefits,improve_prospects,improve_workhours,...,time_household,filters_EU27,monthly_income_eur_imp,monthly_income_eur_imp_ppp,hourly_income_eur_imp,income_quintile_country_weighted,occupation,design_weight,gweight,calweight
count,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,...,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000,36644.000000
mean,17.602309,909.060474,35.186470,1.892779,48.177273,4.563175,581.231334,0.695394,0.264927,0.317842,...,21.036851,0.781056,1823.800829,1963.451699,13.335501,2.903559,15.889013,6045.647118,1.024904,6044.133647
std,10.292970,7649.626488,60.632689,0.830368,24.443581,2.461575,275.497634,0.460247,0.441301,0.465644,...,26.263987,0.413537,1630.787559,1458.498924,24.559638,1.432992,21.921203,10820.448219,0.633671,12872.995011
min,1.000000,2.000000,1.000000,1.000000,1.000000,0.000000,-881.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,8.852571,19.607843,0.070058,1.000000,1.000000,52.521327,0.030000,3.311127
25%,9.000000,10.000000,11.000000,1.000000,25.000000,2.000000,450.000000,0.000000,0.000000,0.000000,...,3.500000,1.000000,788.514769,1052.631579,4.788462,2.000000,2.000000,990.382343,0.582947,773.085404
50%,17.000000,20.000000,21.000000,2.000000,51.000000,5.000000,560.000000,1.000000,0.000000,0.000000,...,14.000000,1.000000,1388.824591,1621.621622,8.695585,3.000000,5.000000,2567.552622,0.948704,2173.920361
75%,26.000000,29.000000,34.000000,3.000000,71.000000,7.000000,850.000000,1.000000,1.000000,1.000000,...,28.000000,1.000000,2440.065341,2500.000000,15.865385,4.000000,30.000000,5137.744517,1.369339,5173.767254
max,35.000000,69657.000000,607.000000,3.000000,96.000000,9.000000,990.000000,1.000000,1.000000,1.000000,...,168.000000,1.000000,68785.252440,59813.262990,1677.621436,5.000000,67.000000,225935.768900,6.612654,392423.299100

In [14]:
#check missing value

missing_table = pd.DataFrame({
    'Missing_Count': df.isnull().sum(),
    'Missing_Percent': missing_percent
})

missing_table.sort_values(
    by='Missing_Percent',
    ascending=False
).head(20)

                  Missing_Count  Missing_Percent
calweight                     0              0.0
uniquerespid                  0              0.0
boss_conf                     0              0.0
boss_cooperation              0              0.0
boss_respect                  0              0.0
wellbeing                     0              0.0
time_household                0              0.0
time_housework                0              0.0
time_elders                   0              0.0
time_children                 0              0.0
days_commuted                 0              0.0
commute_time                  0              0.0
contracted_hours              0              0.0
usual_hours                   0              0.0
supervising_num               0              0.0
hh_soleworker                 0              0.0
hh_nochilds                   0              0.0
hh_single                     0              0.0
num_supervising               0              0.0
female_coworkers              0              0.0

In [15]:
#find suspicious values

for col in df.columns:

    if (df[col].dtype == 'int64') or (df[col].dtype == 'float64'):

        print(col)
        print(df[col].nunique())
        print(df[col].sort_values().unique()[:10])
        print("----------------")

country
35
[ 1  2  3  4  5  6  7  8  9 10]
----------------
language
31
[ 2  3  5  6  7  8  9 10 11 12]
----------------
householdnumber
510
[ 1  2  3  4  5  6  7  8  9 10]
----------------
degurba
3
[1 2 3]
----------------
ISCO_2
43
[ 1  2  3 11 12 13 14 21 22 23]
----------------
ISCO_1
10
[0 1 2 3 4 5 6 7 8 9]
----------------
NACE_2
89
[-881    1    2    3    5    6    7    8    9  100]
----------------
improve_pay_benefits
2
[0 1]
----------------
improve_prospects
2
[0 1]
----------------
improve_workhours
2
[0 1]
----------------
improve_health_safety
2
[0 1]
----------------
improve_social
2
[0 1]
----------------
improve_opportunities
2
[0 1]
----------------
improve_workload
2
[0 1]
----------------
improve_voice
2
[0 1]
----------------
improve_DK
2
[0 1]
----------------
improve_Refused
2
[0 1]
----------------
isced
11
[-999 -998    0    1    2    3    4    5    6    7]
----------------
workstatus
11
[-999 -998    1    2    3    4    5    6    7    8]
----------------
age
59
[16 17 18 19 20 21 22 23 24 25]
----------------
EU27
2
[0 1]
----------------
EU27_EEA
2
[0 1]
----------------
IPA6
2
[0 1]
----------------
EU14
2
[0 1]
----------------
EU11
2
[0 1]
----------------
language_interview
1
[0]
----------------
hh_numchild
8
[0 1 2 3 4 5 6 7]
----------------
hh_numchild_lt5
5
[0 1 2 3 4]
----------------
hh_numchild_gt5
7
[0 1 2 3 4 5 6]
----------------
hh_numadult
10
[0 1 2 3 4 5 6 7 8 9]
----------------
hh_nochilds
2
[0 1]
----------------
time_household
500
[0.         0.01666667 0.03333333 0.05       0.08333333 0.11666667
 0.16666667 0.23333333 0.25       0.33333333]
----------------
filters_EU27
2
[0 1]
----------------
monthly_income_eur_imp
9865
[ 8.85257065 16.66666667 16.87755469 17.52838717 17.7051413  18.79018502
 20.         20.01099424 20.02012173 20.44735562]
----------------
monthly_income_eur_imp_ppp
11447
[19.60784314 21.59163573 22.10610003 23.52941176 23.54234616 23.68700969
 24.62973454 25.04545353 25.24364891 27.10571673]
----------------
hourly_income_eur_imp
13513
[0.07005785 0.09625058 0.09737051 0.10840491 0.11440318 0.11557178
 0.11573007 0.11796551 0.12549573 0.12715384]
----------------
income_quintile_country_weighted
5
[1 2 3 4 5]
----------------
occupation
8
[ 1  2  4  5  8  9 30 67]
----------------
design_weight
2453
[ 52.52132722  59.10562761  66.22254301  66.83405398  69.23265861
  82.28886763  84.61769385  98.74664115 100.4795669  104.5718928 ]
----------------
gweight
23249
[0.03       0.04501343 0.05       0.05016755 0.0518962  0.05721464
 0.05757141 0.0579117  0.05906677 0.05932849]
----------------
calweight
30752
[3.31112715 3.46163293 4.11444338 5.25213272 6.6222543  6.6834054
 6.6834054  6.92326586 6.98656543 6.98719655]
----------------

In [16]:
# replace suspicious values

df.replace([-999, -998, -881], np.nan, inplace=True)

#re-check missing values again after replacement of suspicious values
(df.isnull().sum().sort_values(ascending=False)).head(20)

NACE_2                         160
isced                           88
workstatus                      33
goodjob_pay                      0
goodjob_aut                      0
exhaust_emot                     0
exhaust_phys                     0
eng_timeflies                    0
eng_enthusiastic                 0
eng_energy                       0
opp_impr_skills                  0
easy_similarjob                  0
qual_ins                         0
who5_cheerful                    0
org_motivates                    0
ask_better_working_contions      0
recognition                      0
prospects                        0
er_balance                       0
who5_interesting                 0
dtype: int64

In [17]:
#check duplicates
df.duplicated().sum()

np.int64(0)

In [20]:
#before this step, missing values were not replaced, now replacing missing values

#Numerical Columns → Median Imputation

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

#Categorical Columns → Mode Imputation

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [21]:
#Recheck Missing Values

df.isnull().sum().sum()

np.int64(0)

In [22]:
#identfying single value columns

single_value_cols = []

for col in df.columns:

    if df[col].nunique() <= 1:
        single_value_cols.append(col)

single_value_cols

['language_interview']

In [23]:
#checking for extreme outliers

df.describe().T

,count,mean,std,min,25%,50%,75%,max
country,36644.0,17.602309,10.292970,1.000000,9.000000,17.000000,26.000000,35.000000
language,36644.0,909.060474,7649.626488,2.000000,10.000000,20.000000,29.000000,69657.000000
householdnumber,36644.0,35.186470,60.632689,1.000000,11.000000,21.000000,34.000000,607.000000
degurba,36644.0,1.892779,0.830368,1.000000,1.000000,2.000000,3.000000,3.000000
ISCO_2,36644.0,48.177273,24.443581,1.000000,25.000000,51.000000,71.000000,96.000000
ISCO_1,36644.0,4.563175,2.461575,0.000000,2.000000,5.000000,7.000000,9.000000
NACE_2,36644.0,587.523223,257.925027,1.000000,450.000000,560.000000,850.000000,990.000000
improve_pay_benefits,36644.0,0.695394,0.460247,0.000000,0.000000,1.000000,1.000000,1.000000
improve_prospects,36644.0,0.264927,0.441301,0.000000,0.000000,0.000000,1.000000,1.000000
improve_workhours,36644.0,0.317842,0.465644,0.000000,0.000000,0.000000,1.000000,1.000000
improve_health_safety,36644.0,0.247953,0.431830,0.000000,0.000000,0.000000,0.000000,1.000000
improve_social,36644.0,0.159153,0.365824,0.000000,0.000000,0.000000,0.000000,1.000000
improve_opportunities,36644.0,0.225958,0.418217,0.000000,0.000000,0.000000,0.000000,1.000000
improve_workload,36644.0,0.245606,0.430452,0.000000,0.000000,0.000000,0.000000,1.000000
improve_voice,36644.0,0.148619,0.355718,0.000000,0.000000,0.000000,0.000000,1.000000
improve_DK,36644.0,0.057881,0.233522,0.000000,0.000000,0.000000,0.000000,1.000000
improve_Refused,36644.0,0.010234,0.100644,0.000000,0.000000,0.000000,0.000000,1.000000
isced,36644.0,4.194520,1.815760,0.000000,3.000000,3.000000,6.000000,8.000000
workstatus,36644.0,1.471346,1.367065,1.000000,1.000000,1.000000,1.000000,9.000000
age,36644.0,44.723884,13.367880,16.000000,34.000000,45.000000,55.000000,74.000000
EU27,36644.0,0.781056,0.413537,0.000000,1.000000,1.000000,1.000000,1.000000
EU27_EEA,36644.0,0.835198,0.371007,0.000000,1.000000,1.000000,1.000000,1.000000
IPA6,36644.0,0.164802,0.371007,0.000000,0.000000,0.000000,0.000000,1.000000
EU14,36644.0,0.415129,0.492751,0.000000,0.000000,0.000000,1.000000,1.000000
EU11,36644.0,0.331296,0.470686,0.000000,0.000000,0.000000,1.000000,1.000000
language_interview,36644.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
hh_numchild,36644.0,0.569861,0.899292,0.000000,0.000000,0.000000,1.000000,7.000000
hh_numchild_lt5,36644.0,0.195530,0.507887,0.000000,0.000000,0.000000,0.000000,4.000000
hh_numchild_gt5,36644.0,0.374304,0.717158,0.000000,0.000000,0.000000,1.000000,6.000000
hh_numadult,36644.0,2.131318,1.245400,0.000000,2.000000,2.000000,3.000000,9.000000
hh_nochilds,36644.0,0.654486,0.475542,0.000000,0.000000,1.000000,1.000000,1.000000
time_household,36644.0,21.036851,26.263987,0.000000,3.500000,14.000000,28.000000,168.000000
filters_EU27,36644.0,0.781056,0.413537,0.000000,1.000000,1.000000,1.000000,1.000000
monthly_income_eur_imp,36644.0,1823.800829,1630.787559,8.852571,788.514769,1388.824591,2440.065341,68785.252440
monthly_income_eur_imp_ppp,36644.0,1963.451699,1458.498924,19.607843,1052.631579,1621.621622,2500.000000,59813.262990
hourly_income_eur_imp,36644.0,13.335501,24.559638,0.070058,4.788462,8.695585,15.865385,1677.621436
income_quintile_country_weighted,36644.0,2.903559,1.432992,1.000000,2.000000,3.000000,4.000000,5.000000
occupation,36644.0,15.889013,21.921203,1.000000,2.000000,5.000000,30.000000,67.000000
design_weight,36644.0,6045.647118,10820.448219,52.521327,990.382343,2567.552622,5137.744517,225935.768900
gweight,36644.0,1.024904,0.633671,0.030000,0.582947,0.948704,1.369339,6.612654
calweight,36644.0,6044.133647,12872.995011,3.311127,773.085404,2173.920361,5173.767254,392423.299100

In [24]:
#Identify Binary vs Categorical vs Continuous Variables

binary_cols = []
continuous_cols = []
categorical_encoded_cols = []

In [25]:
#Class Balance of Important Variables

df['improve_workload'].value_counts()

improve_workload
0    27644
1     9000
Name: count, dtype: int64

In [26]:
#SAVE CLEANED VERSION

df.to_csv(
    '/content/drive/MyDrive/Artefact V2/EWCS2024_Cleaned.csv',
    index=False
)