<a href="https://colab.research.google.com/github/angarikadas26-lgtm/burnout-prediction-project/blob/main/ArtifactV2_datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install pandas numpy matplotlib seaborn scikit-learn xgboost shap

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (0.51.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap) (4.67.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from shap) (0.60.0)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.12/dist-packages (from shap) (0.43.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# IS6611 Applied Research in Business Analytics
# Employee Burnout Prediction
# Group 6

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#read file
df = pd.read_csv(
    '/content/drive/MyDrive/Artefact V2/2024_Eurofound_working_conditions.csv')

/tmp/ipykernel_3907/1709392518.py:2: DtypeWarning: Columns (9,16,43,44,46,48,52,54,55,62,101,102,110,111,127,133,208,212,217,232,243,245,256,258,259,260,288,324,325,334,366,378) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [6]:
#data description
df.head()
df.shape

(36644, 386)

In [7]:
#Step 1-understand (analyze) & clean data
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36644 entries, 0 to 36643
Columns: 386 entries, uniquerespid to calweight
dtypes: float64(7), int64(34), object(345)
memory usage: 107.9+ MB

uniquerespid       0
country_code       0
country            0
language           0
samplingpointid    0
                  ..
sector             0
region             0
design_weight      0
gweight            0
calweight          0
Length: 386, dtype: int64

In [8]:
#check missing values
missing_values = df.isnull().sum()

missing_values.sort_values(ascending=False)

calweight           0
uniquerespid        0
boss_conf           0
boss_cooperation    0
boss_respect        0
                   ..
stratumid           0
householdnumber     0
samplingpointid     0
language            0
country             0
Length: 386, dtype: int64

In [9]:
#Missing Percentage

missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent.sort_values(ascending=False)

calweight           0.0
uniquerespid        0.0
boss_conf           0.0
boss_cooperation    0.0
boss_respect        0.0
                   ...
stratumid           0.0
householdnumber     0.0
samplingpointid     0.0
language            0.0
country             0.0
Length: 386, dtype: float64